recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LdG2wYAAAAAADzsdqLb_tsxRt5hA4lC39Mj7u8l"
	privateKey = "6LdG2wYAAAAAAKAVYfI99Budqn8QrYZBYyrBSEur"

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}